version: 7.20.{build}
configuration: Release
platform: Any CPU
environment:
  NSISDIR: 'C:\Program Files (x86)\NSIS'
  MSVCDIR: 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build'
  matrix:
  - QTDIR: C:\Qt\5.14\msvc2017
    VCVARS: vcvars32.bat
    NSI: gpxsee.nsi
    OPENSSLDIR: C:\OpenSSL-v111-Win32\bin
    LIBCRYPTO: libssl-1_1.dll
    LIBSSL: libcrypto-1_1.dll
  - QTDIR: C:\Qt\5.14\msvc2017_64
    VCVARS: vcvars64.bat
    NSI: gpxsee64.nsi
    OPENSSLDIR: C:\OpenSSL-v111-Win64\bin
    LIBCRYPTO: libssl-1_1-x64.dll
    LIBSSL: libcrypto-1_1-x64.dll    
install:
- cmd: >-
    set PATH=%QTDIR%\bin;%NSISDIR%;%PATH%

    call "%MSVCDIR%\%VCVARS%"

build_script:
- cmd: >-
    lrelease gpxsee.pro

    qmake gpxsee.pro

    nmake release


    md installer

    copy release\GPXSee.exe installer

    windeployqt --no-svg --release installer\GPXSee.exe

    copy pkg\%NSI% installer

    copy pkg\macros.nsh installer

    xcopy pkg\csv installer\csv /i

    xcopy pkg\maps installer\maps /i

    xcopy lang\*.qm installer\translations\ /sy

    copy licence.txt installer

    copy %OPENSSLDIR%\%LIBCRYPTO% installer

    copy %OPENSSLDIR%\%LIBSSL% installer


    makensis.exe installer\%NSI%
artifacts:
- path: installer\GPXSee-*.exe
